# Site settings
title: selenehienclone.github.io
description: Description of your GitHub Pages site
theme: jekyll-theme-minimal

# GitHub Pages settings
repository: selenehienclone/selenehienclone.github.io # Replace with your GitHub username and repository name
branch: main # Replace with your default branch name (usually "main" or "master")

# Build settings
markdown: kramdown
permalink: /:title/
exclude: ['Gemfile', 'Gemfile.lock', 'node_modules', 'Rakefile', 'README.md', '_config.yml']
